#!/usr/bin/env bash

declare -a node_themes=(
  "ace"
  "apage"
  "austinmcconnell"
  "boldstatement"
  # "briefstrap"
  "business-card"
  "caffeine"
  "class"
  "classy"
  "compact-extended"
  "contempo"
  "crisp"
  "curzy"
  "cvstrap"
  "dave"
  "demo"
  "developpez"
  "elegant-jali"
  "elegant-mrseanryan"
  "elegantfixed"
  "elephant"
  "elite"
  "eternal"
  "even"
  "flat"
  "flat-optimized"
  "fresh"
  # "genocation"
  "github"
  "kards"
  "kcv"
  "kendall-beardtree"
  "kendall-custom"
  "kendall-felipecrs"
  "kendall-gren"
  "kendall-ksenia"
  "kwan-linkedin"
  "lowmess"
  "lukemeads"
  "macchiato"
  "macchiato-ibic"
  "markdown"
  "material"
  "md"
  "moon"
  # "material-design"
  "material-moon"
  "msresume"
  "nl-flat"
  "onepage-mrseanryan"
  "orbit"
  "orbit-original"
  "paper-v2"
  "papirus"
  "polymer"
  "print-flexbox"
  "psimple"
  "protos"
  "pumpkin"
  "qimia"
  "randytarampi"
  "ravgift"
  "rocketspacer"
  "samk"
  "simple-red"
  "simplistic"
  "smart"
  "so-moon"
  "spartan"
  "spartan-extended"
  "stackoverflow-ibic"
  # "stackoverflow2"
  "standard-resume"
  "tachyons-clean"
  # "tan-responsive"
  "techlead"
  "timeline-fixed"
  "tyler"
  "spartacus-prime"
  "stackoverflow-skills"
  "mocha-responsive"
  "mint"
  "stackoverflow-marion"
  "stackoverflow-skills-below-education"
  "pinage404"
  "stackoverflow-plus"
  "compactbr"
  "spartacus"
  "skills"
  "printclassy"
  "onepage-simplified"
  "umennel"
  "keloran"
  "short-stephenfork"
  "slick"
  "dark-classy-responsive"
  "sceptile"
  "light-classy-concise"
  "cora"
  "srt"
  "elegantnew"
  "simplyelegant"
  "qlh"
  "direct"
  "lemonlabs"
  "shorter"
  "srt-it"
  "trivento"
  "elegantprofile"
  "flat-projects"
  "elegant-leonth"
  "elegant-custom"
  "dark-classy"
  "light-classy-responsive"
  "kate"
  "light-classy-responsive-m2"
  "elegant-projects"
  "resu"
  "joeytall"
  "zurb"
  "foxyboxy"
  "striking"
  "hydejack"
  "plick"
  "protos"
  "minimal"
  "papier"
  "shorter-miles"
  "slick-bentley"
  "sidepanel"
  "mu"
  "paper-condensed"
  "spartan-skills"
  "ankurclass"
  "retro"
  "paper-fixed"
  "paper-monofont"
  "ifyoumakeit"
  "materialize"
  "haosio"
  "clean"
  "sergio"
  "srt-it"
  "srt-epost"
  "onepage-ds"
  "spartan-skills-de"
  "concise-serif"
  "dark-classy-edit"
  "semantic-ui"
  "shorter-bill"
  "onepageresume-alt"
  "jsonresume-theme-slicker"
  "joomla-flats"
  "short-newmanrsfork"
  "robin"
  "flat-extended"
  "simplistic"
  "eddywashere"
  "sheerun"
  "awolden"
  "flatphill"
  "fizz"
  "next"
  "onepage-nderkach"
  "trivento"
  "onepage-efficient"
  "classic"
  "short-remix"
  "onepage-wide"
  "minimalism"
  "business"
  "rhinebeck"
  "paper-plus-plus"
  "uppsala"
  "kwan"
  "morki"
  "student-onepage"
  "modern"
  "juno"
  "jjlorenzoelegant"
  "refined"
  "kwan-fix"
  "wb-elegant"
  "class2"
  "elegant-compact"
  "elegant-wso"
  "elegant-hitesh"
)

# declare -a git_themes=(
#   "aaccurso"
#   # "bluestars"
#   "developpez"
#   "elegant-tony"
#   "funky"
#   "hopian"
#   "kendall-custom"
#   # "material-design"
#   "riga"
#   "sebastianblei"
# )


function generate_theme () {
  printf "generating theme with %s...\n" "$1"
  hackmyresume build "matthew.ogram.resume.json" TO "out/gen/$1/resume.mjo.all" -t "$1"
  # open "out/gen/{1}/resume.mjo.html"
  pageres "out/gen/$1/resume.mjo.html" --filename="resume.mjo.$1" --overwrite
  cp "out/gen/$1/resume.mjo.$1,png" "out/img/"
  # rate_theme, echo "$1" # arguments are accessible through generate_theme...,...
}

# TODO: asyncronnous
printf "---------------- node themes -------------------\n"
for item in "${node_themes[@]}"; do {
  generate_theme "node_modules/jsonresume-theme-${item}" &
  printf "--> creating standard npm-based themes...\n"
  echo "$item"
};
done
printf "--------------------------------------------------\n"

printf "---------------- git themes --------------------\n"
# TODO: avoid non-npm themes for now
# for item in "${git_themes[@]}"; do {
#   generate_theme "themes/jsonresume-theme-$item" &
#   printf "--> creating extra non-npm themes (git-based)...\n"
#   echo "$item"
# };
# done
printf "--------------------------------------------------\n"
